name: Site Generator

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:

  generate_site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: "maven"
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Build site
        run: mvn site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy site
        uses: actions/upload-pages-artifact@v1.0.1
        with: 
            path: target/site

  publish_docs:
    runs-on: ubuntu-latest
    needs: generate_site
    permissions:
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.generate_site.outputs.pages_url }}
    
